### ISSUE TITLE
Using containers with VirtualMachines child type introduce invalid characters

### ISSUE THREAD

**Issue by dewjam** [SYNAXON/GraphiteReceiver#13]
When specifying a container with VirtualMachines as a Child Type, the container name is added as a prefix within brackets. For instance, if the container is a folder called “Testing” with a VM inside called “server1″, the name of the node ends up being “[Testing]server1″ in Graphite/Whisper. Data seems to be written properly, but I can’t retrieve any of the metrics through Graphite browser (or Grafana). I’ve done some testing and I’m certain it’s due to the brackets.  If I manually rename the folder to “server1″, I then can see all of the metrics.  

Can the container name be removed from the node name entirely?  Or could there be an option to add the container to the graphite tree?

For Example:
<prefix>.<entity_type>.<CONTAINER>.<entity_name>.<metric_group>.<instance_name>.<counter_name>.<rollup>_<statistic_type

**Comment by ikkaro** [comment]
Hi,

I've the same issue.
If the cluster name is "CLUSTER-A" the folder for the VM metric is named "[CLUSTER-A]vm_name" and using grafana you can't get the metric correctly.

**Comment by toni-moreno** [comment]
Hi @ikkaro @dewjam , this is a know bug that I can fix  ASAP , but I would like to do it when mergen a new feature in https://github.com/SYNAXON/GraphiteReceiver/pull/12 

@kofrezo @datenbrille , when do you have plans to merge this new PR ?

Thanks!

**Comment by kofrezo** [comment]
Done! ;-)

**Comment by dewjam** [comment]
Awesome!  Thanks for the quick fix!  I'll test it out and then close out the issue.

**Comment by toni-moreno** [comment]
ok @kofredo, I will try to fix this issue , next week. 

@dewjam: @kofredo did the previous merge , not the fix ,  yet !!!
