### ISSUE TITLE
all samples - still downsampled to 1 minute?

### ISSUE THREAD

**Issue by ghost** [SYNAXON/GraphiteReceiver#21]
Hi,
I have configured in the config file.

```
                <name>only_one_sample_x_period</name>
                <value>false</value>
```

The log file shows:
300656 [Thread-257] DEBUG de.synaxon.graphitereceiver.MetricsReceiver  - all samples

I should see a datapoint every 20s, but still I only see 1 each minute.
Can you help me out?

**Comment by toni-moreno** [comment]
Sorry , for the late response @owange 

 how do you fix this issue?

Thank you !

**Comment by ghost** [comment]
This was a misconfiguration of graphite. I was so sure i had the correct information in the storage-schema.xml that i overlooked a typo. So it wasn't a issue with the receiver :)
