### ISSUE TITLE
Cluster Host Mapping multiple times initializated

### ISSUE THREAD

**Issue by toni-moreno** [SYNAXON/GraphiteReceiver#28]
Hi @lbasavap We are doing some test and detected a strange thing. Could be possible that Graphite Receiver are doing the same thing three times?

```
# grep "initClusterHostMap Begin" esxvm_stats.log
2015-10-09 10:39:55,340 [Thread-8] DEBUG Utils  - initClusterHostMap Begin
2015-10-09 10:39:55,351 [Thread-8] DEBUG Utils  - initClusterHostMap Begin
2015-10-09 10:39:55,365 [Thread-8] DEBUG Utils  - initClusterHostMap Begin
```

I'm trying also review the remap period but, I can't understand how often GraphiteReceiver are doing the remap.

We have this config 

```
               <property>
                    <name>cluster_map_refresh_timeout</name>
                    <value>3600</value>
                </property>
```

but I can not remember what 3600 is, could you tell me what exactly means?

**Comment by lbasavap** [comment]
Hello Toni;
3600 seconds or one hour. But log indicates init happened within one second; this could be because receiver found new entities - VM or ESX or exception detected. I will take look later today. 

Thanks

Lava

**Comment by toni-moreno** [comment]
Hi @lbasavap , @cosm0s  has already reviewed this point and he told me the reason of this debug log. But Initialization is done only once.

Thank you very much @cosm0s

**Comment by lbasavap** [comment]
Thank you, all
