### ISSUE TITLE
Datastores entities: The cluster is null

### ISSUE THREAD

**Issue by vmwiz** [SYNAXON/GraphiteReceiver#42]
While gathering datastores stats nothing is written to graphite backend

`[Thread-3] DEBUG MetricsReceiver  - MetricsReceiver in receiveStats`
`[Thread-3] DEBUG MetricsReceiver  - Container Name :null Interval: 300 Frequency :60`
`[Thread-3] DEBUG Utils  - GP :ESX EN:  CN: disk.capacity.provisioned.average ST: kiloBytes`
`[Thread-3] DEBUG Utils  - The cluster is null -`

[graphiteConfig.txt](https://github.com/SYNAXON/GraphiteReceiver/files/152466/graphiteConfig.txt)

**Comment by toni-moreno** [comment]
Hi @vmwiz , it seems that code always looks for  cluster containing  current entity . But this condition never happens on datastore type entities.

**Comment by vmwiz** [comment]
Would such piece of code be an easy fix?

src/main/java/de/synaxon/graphitereceiver/core/MetricsReceiver.java::286 

``` java
if((metricSet.getEntityName().contains("Datastore")){
          cluster = "vcGlobal";
}
```

**Comment by G-regL** [comment]
Another option would be to nest hosts/clusters inside their respective Datacenters, thereby allowing entities to be logically grouped, just like in vCenter. It would be a breaking change and should probably have a configuration switch to allow for backwards compatibility. 

This of course assumes that Datacenter names are being exposed via the StatsFeeder...
