### ISSUE TITLE
Feature Request: get DataCenter/Cluster container for each Host ESX/VM. 

### ISSUE THREAD

**Issue by toni-moreno** [SYNAXON/GraphiteReceiver#9]
IT could be great if we can add DataCenter/Cluster Name to the graphite tree. 

With PR (https://github.com/SYNAXON/GraphiteReceiver/pull/7)  we have this tree.

```
<prefix>.<entity_type>.<entity_name>.<metric_group>.<instance_name>.<counter_name>.<rollup>_<statistic_type>

```

Could be great to get:

```
<prefix>.<DATACENTER>.<CLUSTER>.<entity_type>.<entity_name>.<metric_group>.<instance_name>.<counter_name>.<rollup>_<statistic_type>

```

**Comment by toni-moreno** [comment]
Anybody has information about "com.vmware.ee.statsfeeder.*"  classes ?

Anybody knows how to get context information on  (https://github.com/SYNAXON/GraphiteReceiver/blob/master/src/main/java/de/synaxon/graphitereceiver/MetricsReceiver.java#L82-L93) ?

how can we get inventory hashmap to get DATACENTER , CLUSTER for each vm or host esx ?

**Comment by tmonk42** [comment]
We've done some work on this, doing code clean up and review before submitting a PR.

**Comment by toni-moreno** [comment]
Hi @tmonk42 , I will be extremely grateful if you can share your code with us!!.

Could be interesting merge your PR with mine (https://github.com/SYNAXON/GraphiteReceiver/pull/7) to add more configuration flexibility  to this receiver.

Thank you !!

**Comment by lbasavap** [comment]
Hello Toni,
I am working on merging my changes with the latest. After I complete initial test I will merge my changes. Thanks for waiting.

Regards

Lava

**Comment by toni-moreno** [comment]
Hi @lbasavap , I'll be waiting for that PR !!

**Comment by toni-moreno** [comment]
Is time to close this Issue!! , we can work with Cluster , not yet with Datacenter but it's ok right now.
